In [2]:
import pandas as pd

In [3]:
beach_data = "data/beach_monthly.csv"
incident_data = "data/incidents.csv"
pricing_data = "data/pricing.csv"

beach_df = pd.read_csv(beach_data)
incident_df = pd.read_csv(incident_data)
pricing_df = pd.read_csv(pricing_data)

In [4]:
beach_df

,beach_nm,postcode,month,visitors,shore_len_m,n_rips,air_temp_hi,swell_avg_m,swell_max_m,wind_days,...,flags,patrolled,equip_rating,rocky,fishing,n_bins,rockpool,icecream_visits,surfer_prop,marine_health
0,Bondi Beach,2026,09/2016,67164,546,3.1,17.9,0.91,1.94,14,...,1,1,78,0,0,46,0,3.6,0.160,M
1,Bondi Beach,2026,10/2016,135166,546,3.1,21.0,0.51,0.93,12,...,1,1,78,0,0,46,0,5.1,0.108,M
2,Bondi Beach,2026,11/2016,159258,546,3.1,23.3,0.63,1.34,12,...,1,1,78,0,0,46,0,4.8,0.139,H
3,Bondi Beach,2026,12/2016,195090,546,3.1,24.4,0.64,1.10,6,...,1,1,78,0,0,46,0,5.5,0.139,H
4,Bondi Beach,2026,01/2017,264337,546,3.1,25.8,1.05,2.22,6,...,1,1,78,0,0,46,0,6.0,0.107,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9595,Aslings Beach (Eden),2551,04/2026,5073,583,2.8,19.9,0.64,1.19,5,...,1,1,48,0,1,11,1,3.4,0.112,L
9596,Aslings Beach (Eden),2551,05/2026,2379,583,2.8,19.1,1.35,2.55,5,...,1,0,48,0,1,11,1,1.6,0.205,L
9597,Aslings Beach (Eden),2551,06/2026,1914,583,2.8,19.4,1.29,2.77,11,...,1,0,48,0,1,11,1,1.3,0.179,L
9598,Aslings Beach (Eden),2551,07/2026,2133,583,2.8,15.0,1.37,2.78,6,...,1,0,48,0,1,11,1,0.4,0.150,M
9599,Aslings Beach (Eden),2551,08/2026,1984,583,2.8,15.4,1.43,2.74,10,...,1,0,48,0,1,11,1,1.7,0.158,L

In [5]:
incident_df

,incident_id,person_no,dte_reported,dte_occurred,inc_hour,inc_type,inc_cause,age,sex,surfer,swim_level,local_ind,response_min,beach_nm,n_lifeguards,drone_present,alone
0,1,1,01/09/2016,01/09/2016,8,Mild,Swimming_Incident,72,M,0.0,beginner,not_local,4.5,North Wollongong Beach,2,N,1
1,2,1,01/09/2016,01/09/2016,9,Mild,Physical_injury,30,M,0.0,experienced,local,4.7,Maroubra Beach,1,N,0
2,3,1,01/09/2016,01/09/2016,9,CloseCall,Swimming_Incident,41,M,NaN,intermediate,not_local,41.0,Merimbula Main Beach,0,N,1
3,4,1,01/09/2016,01/09/2016,10,Mild,Swimming_Incident,9,M,0.0,beginner,not_local,5.2,Manly Beach,2,N,0
4,5,1,01/09/2016,01/09/2016,11,CloseCall,Swimming_Incident,39,F,0.0,intermediate,not_local,4.1,North Wollongong Beach,1,N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33936,32455,1,31/08/2026,31/08/2026,12,Mild,Swimming_Incident,22,M,0.0,intermediate,local,30.8,Redhead Beach,0,N,0
33937,32456,1,31/08/2026,31/08/2026,13,Mild,Swimming_Incident,16,M,0.0,intermediate,local,13.4,Kiama Surf Beach,0,N,0
33938,32457,1,31/08/2026,31/08/2026,14,Mild,Swimming_Incident,61,F,0.0,intermediate,local,1.6,Bondi Beach,4,N,0
33939,32458,1,31/08/2026,31/08/2026,14,Mild,Swimming_Incident,4,M,0.0,beginner,local,4.4,Bondi Beach,4,N,0
33940,32459,1,31/08/2026,31/08/2026,17,Mild,Swimming_Incident,25,F,NaN,intermediate,not_local,14.0,Dee Why Beach,0,N,0

In [6]:
incident_df["person_no"].count()

np.int64(33941)

In [7]:
incident_df["dte_occurred"] = pd.to_datetime(incident_df["dte_occurred"], format="%d/%m/%Y")
incident_df["month"] = incident_df["dte_occurred"].dt.strftime("%m/%Y")
incident_df["month"]

0        09/2016
1        09/2016
2        09/2016
3        09/2016
4        09/2016
          ...
33936    08/2026
33937    08/2026
33938    08/2026
33939    08/2026
33940    08/2026
Name: month, Length: 33941, dtype: str

In [8]:
incident_df

,incident_id,person_no,dte_reported,dte_occurred,inc_hour,inc_type,inc_cause,age,sex,surfer,swim_level,local_ind,response_min,beach_nm,n_lifeguards,drone_present,alone,month
0,1,1,01/09/2016,2016-09-01,8,Mild,Swimming_Incident,72,M,0.0,beginner,not_local,4.5,North Wollongong Beach,2,N,1,09/2016
1,2,1,01/09/2016,2016-09-01,9,Mild,Physical_injury,30,M,0.0,experienced,local,4.7,Maroubra Beach,1,N,0,09/2016
2,3,1,01/09/2016,2016-09-01,9,CloseCall,Swimming_Incident,41,M,NaN,intermediate,not_local,41.0,Merimbula Main Beach,0,N,1,09/2016
3,4,1,01/09/2016,2016-09-01,10,Mild,Swimming_Incident,9,M,0.0,beginner,not_local,5.2,Manly Beach,2,N,0,09/2016
4,5,1,01/09/2016,2016-09-01,11,CloseCall,Swimming_Incident,39,F,0.0,intermediate,not_local,4.1,North Wollongong Beach,1,N,0,09/2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33936,32455,1,31/08/2026,2026-08-31,12,Mild,Swimming_Incident,22,M,0.0,intermediate,local,30.8,Redhead Beach,0,N,0,08/2026
33937,32456,1,31/08/2026,2026-08-31,13,Mild,Swimming_Incident,16,M,0.0,intermediate,local,13.4,Kiama Surf Beach,0,N,0,08/2026
33938,32457,1,31/08/2026,2026-08-31,14,Mild,Swimming_Incident,61,F,0.0,intermediate,local,1.6,Bondi Beach,4,N,0,08/2026
33939,32458,1,31/08/2026,2026-08-31,14,Mild,Swimming_Incident,4,M,0.0,beginner,local,4.4,Bondi Beach,4,N,0,08/2026
33940,32459,1,31/08/2026,2026-08-31,17,Mild,Swimming_Incident,25,F,NaN,intermediate,not_local,14.0,Dee Why Beach,0,N,0,08/2026

In [9]:
aggregated_df = incident_df.groupby(["month", "beach_nm"]).agg(
    n_incidents=("incident_id", "nunique"),  
    n_people=("incident_id", "size"),        
    n_mild=("inc_type", lambda x: (x == "Mild").sum()),
    n_closecall=("inc_type", lambda x: (x == "CloseCall").sum()),
    n_severe=("inc_type", lambda x: (x == "Severe").sum())
).reset_index()

print(aggregated_df)

        month               beach_nm  n_incidents  n_people  n_mild  \
0     01/2017         Angourie Beach            1         1       1
1     01/2017   Aslings Beach (Eden)            2         2       2
2     01/2017        Austinmer Beach            6         6       5
3     01/2017           Avalon Beach            3         3       3
4     01/2017            Avoca Beach            5         5       5
...       ...                    ...          ...       ...     ...
5895  12/2025            Werri Beach           12        12      11
5896  12/2025  Wollongong City Beach            8         8       8
5897  12/2025       Woolgoolga Beach            1         1       1
5898  12/2025          Woonona Beach            6         6       6
5899  12/2025       Yamba Main Beach            5         5       5

      n_closecall  n_severe
0               0         0
1               0         0
2               1         0
3               0         0
4               0         0
...           ...       ...
5895            1         0
5896            0         0
5897            0         0
5898            0         0
5899            0         0

[5900 rows x 7 columns]

# inc_cause, surfer, has null values

In [10]:
agg = incident_df.groupby(["beach_nm", "month"]).agg(
    n_incidents=("incident_id", "nunique"),
    n_people=("incident_id", "size"),
)
types = (pd.crosstab([incident_df["beach_nm"], incident_df["month"]], incident_df["inc_type"])
           .rename(columns=lambda c: f"n_{c.lower()}"))
agg = agg.join(types).reset_index()

panel = beach_df.merge(agg, on=["beach_nm", "month"], how="left")
cols = ["n_incidents", "n_people", "n_mild", "n_closecall", "n_severe"]
panel[cols] = panel[cols].fillna(0).astype(int)

In [61]:
panel

,beach_nm,postcode,month,visitors,shore_len_m,n_rips,air_temp_hi,swell_avg_m,swell_max_m,wind_days,...,n_bins,rockpool,icecream_visits,surfer_prop,marine_health,n_incidents,n_people,n_closecall,n_mild,n_severe
0,Bondi Beach,2026,09/2016,67164,546,3.1,17.9,0.91,1.94,14,...,46,0,3.6,0.160,M,10,12,2,10,0
1,Bondi Beach,2026,10/2016,135166,546,3.1,21.0,0.51,0.93,12,...,46,0,5.1,0.108,M,54,55,7,46,2
2,Bondi Beach,2026,11/2016,159258,546,3.1,23.3,0.63,1.34,12,...,46,0,4.8,0.139,H,6,6,0,6,0
3,Bondi Beach,2026,12/2016,195090,546,3.1,24.4,0.64,1.10,6,...,46,0,5.5,0.139,H,32,35,3,30,2
4,Bondi Beach,2026,01/2017,264337,546,3.1,25.8,1.05,2.22,6,...,46,0,6.0,0.107,L,61,65,5,60,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9595,Aslings Beach (Eden),2551,04/2026,5073,583,2.8,19.9,0.64,1.19,5,...,11,1,3.4,0.112,L,4,4,1,3,0
9596,Aslings Beach (Eden),2551,05/2026,2379,583,2.8,19.1,1.35,2.55,5,...,11,1,1.6,0.205,L,0,0,0,0,0
9597,Aslings Beach (Eden),2551,06/2026,1914,583,2.8,19.4,1.29,2.77,11,...,11,1,1.3,0.179,L,0,0,0,0,0
9598,Aslings Beach (Eden),2551,07/2026,2133,583,2.8,15.0,1.37,2.78,6,...,11,1,0.4,0.150,M,0,0,0,0,0
9599,Aslings Beach (Eden),2551,08/2026,1984,583,2.8,15.4,1.43,2.74,10,...,11,1,1.7,0.158,L,1,1,0,1,0

In [26]:

bm = beach_df.copy()
bm["month_key"] = pd.to_datetime(bm["month"], format="%m/%Y").dt.to_period("M")   

inc = incident_df.copy()
for c in ["dte_occurred", "dte_reported"]:
    inc[c] = pd.to_datetime(inc[c], format="%d/%m/%Y")
inc["month_key"] = inc["dte_occurred"].dt.to_period("M")   

person = inc.merge(
    bm.drop(columns="month"),
    on=["beach_nm", "month_key"],
    how="left",
    validate="many_to_one",
    indicator=True,
)
assert len(person) == len(incident_df) == 33_941
assert (person["_merge"] == "both").all()
person = person.drop(columns="_merge")

person["incident_size"]   = person.groupby("incident_id")["person_no"].transform("size")
person["on_duty"]         = (person["n_lifeguards"] > 0).astype(int)
person["surfer"]    = person["surfer"].astype("string").fillna("unknown")
person["inc_cause"] = person["inc_cause"].fillna("unknown")      
person["inc_type"]  = pd.Categorical(person["inc_type"],
                                     categories=["Mild", "CloseCall", "Severe"], ordered=True)

In [28]:
person

,incident_id,person_no,dte_reported,dte_occurred,inc_hour,inc_type,inc_cause,age,sex,surfer,...,equip_rating,rocky,fishing,n_bins,rockpool,icecream_visits,surfer_prop,marine_health,incident_size,on_duty
0,1,1,2016-09-01,2016-09-01,8,Mild,Swimming_Incident,72,M,0.0,...,50,0,0,45,1,3.9,0.178,H,1,1
1,2,1,2016-09-01,2016-09-01,9,Mild,Physical_injury,30,M,0.0,...,58,1,1,57,0,3.2,0.144,H,1,1
2,3,1,2016-09-01,2016-09-01,9,CloseCall,Swimming_Incident,41,M,unknown,...,48,0,0,19,1,2.0,0.123,M,1,0
3,4,1,2016-09-01,2016-09-01,10,Mild,Swimming_Incident,9,M,0.0,...,76,0,1,44,1,4.4,0.587,H,1,1
4,5,1,2016-09-01,2016-09-01,11,CloseCall,Swimming_Incident,39,F,0.0,...,50,0,0,45,1,3.9,0.178,H,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33936,32455,1,2026-08-31,2026-08-31,12,Mild,Swimming_Incident,22,M,0.0,...,54,1,1,10,0,0.6,0.204,L,1,0
33937,32456,1,2026-08-31,2026-08-31,13,Mild,Swimming_Incident,16,M,0.0,...,88,0,0,26,0,2.6,0.254,M,1,0
33938,32457,1,2026-08-31,2026-08-31,14,Mild,Swimming_Incident,61,F,0.0,...,83,0,0,46,0,3.8,0.126,M,1,1
33939,32458,1,2026-08-31,2026-08-31,14,Mild,Swimming_Incident,4,M,0.0,...,83,0,0,46,0,3.8,0.126,M,1,1
33940,32459,1,2026-08-31,2026-08-31,17,Mild,Swimming_Incident,25,F,unknown,...,67,0,1,45,0,3.1,0.139,M,1,0

In [15]:
panel.to_csv("data/panel.csv", index=False)

In [29]:
person.to_csv("data/person.csv", index=False)